version: "3"
services:

  o2k-connector:
    image: o2k-connector
    build: ./build
    hostname: o2k-connector
    networks:
      - hostnet
    ports:
      - "5050:5050"
    env_file:
      - o2k.env
    volumes:
      - ./conf:/o2k-connector/data
      - ./logs:/o2k-connector/logs
      #- ./Certificates:/o2k-connector/Certificates

networks:
  hostnet:
    external:
      name: network-bridge
